name: Fetch Attendance and Push to Notion

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:  # allows manual triggering

jobs:
  attendance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 python-dotenv

      - name: Run attendance script
        env:
          LMS_USERNAME: ${{ secrets.LMS_USERNAME }}
          LMS_PASSWORD: ${{ secrets.LMS_PASSWORD }}
          Batch_3_COURSE_URLS: ${{ secrets.Batch_3_COURSE_URLS }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: |
          python main.py